import { ALL_CATEGORIES } from "@/constants/transaction.constants";
import type { TranslationSchema } from "@/locales/types";
import type { TransactionCategory, TransactionType } from "@/types";
import { z } from "zod";

export const TRANSACTION_ISSUE_CODES = {
  DESCRIPTION_MIN: "validation.descriptionMin",
  DESCRIPTION_MAX: "validation.descriptionMax",
  AMOUNT_INVALID: "validation.amountInvalid",
  AMOUNT_POSITIVE: "validation.amountPositive",
  TYPE_REQUIRED: "validation.typeRequired",
  CATEGORY_REQUIRED: "validation.categoryRequired",
  DATE_REQUIRED: "validation.dateRequired",
  DATE_FORMAT: "validation.dateFormat",
  DATE_INVALID: "validation.dateInvalid",
} as const;

export type TransactionIssueCode =
  (typeof TRANSACTION_ISSUE_CODES)[keyof typeof TRANSACTION_ISSUE_CODES];

const TRANSACTION_TYPES: readonly [TransactionType, ...TransactionType[]] = ["income", "expense"];

const TRANSACTION_CATEGORIES: readonly [TransactionCategory, ...TransactionCategory[]] =
  ALL_CATEGORIES;

export const createTransactionSchema = z
  .object({
    description: z
      .string({ message: TRANSACTION_ISSUE_CODES.DESCRIPTION_MIN })
      .trim()
      .min(3, { message: TRANSACTION_ISSUE_CODES.DESCRIPTION_MIN })
      .max(60, { message: TRANSACTION_ISSUE_CODES.DESCRIPTION_MAX }),

    amount: z
      .number({ message: TRANSACTION_ISSUE_CODES.AMOUNT_INVALID })
      .positive({ message: TRANSACTION_ISSUE_CODES.AMOUNT_POSITIVE }),

    type: z.enum(TRANSACTION_TYPES, {
      message: TRANSACTION_ISSUE_CODES.TYPE_REQUIRED,
    }),

    category: z.enum(TRANSACTION_CATEGORIES, {
      message: TRANSACTION_ISSUE_CODES.CATEGORY_REQUIRED,
    }),

    date: z
      .string({ message: TRANSACTION_ISSUE_CODES.DATE_REQUIRED })
      .min(1, { message: TRANSACTION_ISSUE_CODES.DATE_REQUIRED })
      .regex(/^\d{4}-\d{2}-\d{2}$/, {
        message: TRANSACTION_ISSUE_CODES.DATE_FORMAT,
      })
      .refine(
        (val) => {
          const [yearStr, monthStr, dayStr] = val.split("-");
          const year = parseInt(yearStr, 10);
          const month = parseInt(monthStr, 10);
          const day = parseInt(dayStr, 10);

          const parsed = new Date(Date.UTC(year, month - 1, day));
          if (isNaN(parsed.getTime())) return false;

          return (
            parsed.getUTCFullYear() === year &&
            parsed.getUTCMonth() === month - 1 &&
            parsed.getUTCDate() === day
          );
        },
        { message: TRANSACTION_ISSUE_CODES.DATE_INVALID }
      ),
  })
  .strict();

export type CreateTransactionSchemaType = typeof createTransactionSchema;
export type CreateTransactionFormData = z.infer<typeof createTransactionSchema>;

/**
 * Translates issue codes generated by the schema into localized messages for the interface.
 */
export function getTranslatedValidationMessage(
  code: string | undefined,
  t: TranslationSchema
): string | undefined {
  if (!code) return undefined;

  switch (code) {
    case TRANSACTION_ISSUE_CODES.DESCRIPTION_MIN:
      return t.validation.descriptionMin;
    case TRANSACTION_ISSUE_CODES.DESCRIPTION_MAX:
      return t.validation.descriptionMax;
    case TRANSACTION_ISSUE_CODES.AMOUNT_INVALID:
      return t.validation.amountInvalid;
    case TRANSACTION_ISSUE_CODES.AMOUNT_POSITIVE:
      return t.validation.amountPositive;
    case TRANSACTION_ISSUE_CODES.TYPE_REQUIRED:
      return t.validation.typeRequired;
    case TRANSACTION_ISSUE_CODES.CATEGORY_REQUIRED:
      return t.validation.categoryRequired;
    case TRANSACTION_ISSUE_CODES.DATE_REQUIRED:
      return t.validation.dateRequired;
    case TRANSACTION_ISSUE_CODES.DATE_FORMAT:
      return t.validation.dateFormat;
    case TRANSACTION_ISSUE_CODES.DATE_INVALID:
      return t.validation.dateInvalid;
    default:
      return code;
  }
}
